POST http://localhost:3000/book
Content-Type: application/json

{
    "title": "IMSAD PTSD", 
    "author": "Naomi",
    "description": "Fighting lang pooo",
    "color": "white"
}

###
GET http://127.0.0.1:3000/book

###
GET http://127.0.0.1:3000/book/

###
DELETE http://127.0.0.1:3000/book/66483cc80ce84b2bdc7d39fc

###
PATCH http://localhost:3000/book/
Content-Type: application/json

{
    "author": "NewLeo"
}

###
PUT http://localhost:3000/book/66471637c3b9dd1c82a0f626
Content-Type: application/json

{
    "title": "Farpsy Lusty", 
    "author": "Leonard",
    "description": "A book about revenge and temptations",
    "color": "white"
}