POST http://localhost:3000/book
Content-Type: application/json

{
    "title": "How to be You po", 
    "author": "Leonard",
    "description": "A book about revenge and temptations",
    "publishYear": 2007
}

###
GET http://127.0.0.1:3000/book

###
GET http://127.0.0.1:3000/book/66470cea76cf483ad1e07240

###
DELETE http://127.0.0.1:3000/book/66470cea76cf483ad1e07240

###
PATCH http://localhost:3000/book/66471637c3b9dd1c82a0f626
Content-Type: application/json

{
    "author": "NewLeo"
}

###
PUT http://localhost:3000/book/66471637c3b9dd1c82a0f626
Content-Type: application/json

{
    "title": "Farpsy Lusty", 
    "author": "Leonard",
    "description": "A book about revenge and temptations",
    "publishYear": 2007
}